#!/bin/bash
VERSION="2.46.3"

source $OPENSHIFT_CARTRIDGE_SDK_BASH
source $OPENSHIFT_REPO_DIR/files/scripts/util

function generate_ssh_keys {
 mkdir -p ${OPENSHIFT_DATA_DIR}/.ssh/
 ssh-keygen -N '' -f ${OPENSHIFT_DATA_DIR}/.ssh/jenkins_id_rsa > /dev/null

 chmod 0750 "${OPENSHIFT_DATA_DIR}/.ssh/"
 chmod 0640 "${OPENSHIFT_DATA_DIR}/.ssh/jenkins_id_rsa"
 chmod 0640 "${OPENSHIFT_DATA_DIR}/.ssh/jenkins_id_rsa.pub"
}

if [ -f ${OPENSHIFT_DATA_DIR}/jenkins-${VERSION}.war ]; then
  echo "Jenkins ${VERSION} was already deployed!"
  exit 0
else
  echo "Downloading Jenkins ${VERSION}..."
  wget -q http://mirrors.jenkins.io/war-stable/${VERSION}/jenkins.war -O ${OPENSHIFT_DATA_DIR}/jenkins-${VERSION}.war
fi

if [ ! -f ${OPENSHIFT_DATA_DIR}jenkins.war ]; then
  echo "First installation..."

  echo "Copying config..."
  cp -r "$OPENSHIFT_REPO_DIR/files/configuration/"* "${OPENSHIFT_DATA_DIR}"

  echo "Generating SSH keys..."
  generate_ssh_keys
  public_key=$(cat ${OPENSHIFT_DATA_DIR}/.ssh/jenkins_id_rsa.pub)
  set -- $public_key
  add_domain_ssh_key "$2"

  echo "Configuring Jenkins..."
  unzip -q /usr/lib/jenkins/jenkins.war -d "${OPENSHIFT_DATA_DIR}/war/"
  openshift_server=`echo "${OPENSHIFT_BROKER_HOST}" | sed -e "s/\/*$//" `
  sed -i "s,OPENSHIFT_SERVER,$openshift_server,g" "${OPENSHIFT_DATA_DIR}/config.xml"
  admin_password=$(generate_password)
  admin_password_hash=`obfuscate_password $admin_password`
  sed -i "s,PASSWORD,$admin_password_hash,g" "${OPENSHIFT_DATA_DIR}/users/admin/config.xml"
  system_builder_password=$(generate_password)
  system_builder_password_hash=`obfuscate_password $system_builder_password`
  sed -i "s,PASSWORD,$system_builder_password_hash,g" "${OPENSHIFT_DATA_DIR}/users/system_builder/config.xml"
  echo $system_builder_password > ${OPENSHIFT_DATA_DIR}/.jenkins_password
  rm -rf ${OPENSHIFT_DATA_DIR}/war/
  
  client_result ""
  client_result "Jenkins created successfully.  Please make note of these credentials:"
  client_result ""
  client_result "   User: admin"
  client_result "   Password: $admin_password"
  client_result ""
  client_result "Note:  You can change your password at: https://${OPENSHIFT_GEAR_DNS}/me/configure"
  client_result ""
  
  cart_props "username=system_builder"
  cart_props "password=$system_builder_password"

  add_domain_env_var "JENKINS_URL=https://${OPENSHIFT_GEAR_DNS}/"
  add_domain_env_var "JENKINS_USERNAME=system_builder"
  add_domain_env_var "JENKINS_PASSWORD=$system_builder_password"
fi

if [ -f ${OPENSHIFT_DATA_DIR}jenkins.war ]; then
  echo "Removing link to Jenkins..."
  rm -f ${OPENSHIFT_DATA_DIR}war/jenkins.war
fi
echo "Link new Jenkins ${VERSION}..."
cp ${OPENSHIFT_DATA_DIR}/jenkins-${VERSION}.war ${OPENSHIFT_DATA_DIR}/jenkins.war
